env:
  browser: true
  es2021: true
parser: '@typescript-eslint/parser'
extends:
  - plugin:react/recommended
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - react
  - '@typescript-eslint'
  - simple-import-sort
  - react-hooks
rules: {}
settings:
  react:
    version: detect
